// Generated by tools/skin_assets.py. Do not edit.
//
// Offsets into `skin_assets.bin`, which is linked in whole by `skin_assets.S` and read
// straight out of memory-mapped flash. Nothing here is copied to RAM: a body is 150 KB and
// never changes, and PSRAM is worth more than a copy of something the flash already holds
// at an address the CPU can read.

#pragma once

#include <cstddef>
#include <cstdint>

namespace assets {

extern const uint8_t kBlobStart[] asm("_binary_src_assets_skin_assets_bin_start");

struct Entry {
    uint32_t offset;
    uint32_t length;
    uint16_t width;
    uint16_t height;
};

inline constexpr Entry kBodyStackchan = {0u, 153600u, 320, 240};
inline constexpr Entry kBodyGhost = {153600u, 153600u, 320, 240};
inline constexpr Entry kBodyFlame = {307200u, 76800u, 320, 240};
inline constexpr Entry kBodyJelly = {384000u, 76800u, 320, 240};
inline constexpr Entry kBodyCloud = {460800u, 76800u, 320, 240};
inline constexpr Entry kEyesNeutral = {537600u, 14784u, 168, 88};
inline constexpr Entry kEyesCalm = {552384u, 14784u, 168, 88};
inline constexpr Entry kEyesJoy = {567168u, 14784u, 168, 88};
inline constexpr Entry kEyesThinking = {581952u, 14784u, 168, 88};
inline constexpr Entry kEyesSurprised = {596736u, 14784u, 168, 88};
inline constexpr Entry kEyesSad = {611520u, 14784u, 168, 88};
inline constexpr Entry kEyesError = {626304u, 14784u, 168, 88};
inline constexpr Entry kEyesClosed = {641088u, 14784u, 168, 88};
inline constexpr Entry kMouthNeutral = {655872u, 8640u, 120, 72};
inline constexpr Entry kMouthCalm = {664512u, 8640u, 120, 72};
inline constexpr Entry kMouthJoy = {673152u, 8640u, 120, 72};
inline constexpr Entry kMouthThinking = {681792u, 8640u, 120, 72};
inline constexpr Entry kMouthSurprised = {690432u, 8640u, 120, 72};
inline constexpr Entry kMouthSad = {699072u, 8640u, 120, 72};
inline constexpr Entry kMouthError = {707712u, 8640u, 120, 72};
inline constexpr Entry kMouthAjar = {716352u, 8640u, 120, 72};
inline constexpr Entry kMouthHalf = {724992u, 8640u, 120, 72};
inline constexpr Entry kMouthWide = {733632u, 8640u, 120, 72};
inline constexpr Entry kMouthOpen = {742272u, 8640u, 120, 72};
inline constexpr Entry kElemGhostBlush = {750912u, 20160u, 168, 40};
inline constexpr Entry kElemGhostTear = {771072u, 2880u, 24, 40};
inline constexpr Entry kElemJellyGlow = {773952u, 72000u, 200, 120};
inline constexpr Entry kElemCloudSun = {845952u, 15552u, 72, 72};
inline constexpr Entry kElemCloudRain = {861504u, 36000u, 200, 60};

inline const uint8_t* bytesOf(const Entry& entry) { return kBlobStart + entry.offset; }
inline const uint16_t* pixelsOf(const Entry& entry) {
    return reinterpret_cast<const uint16_t*>(kBlobStart + entry.offset);
}

inline constexpr std::size_t kBlobBytes = 897504u;

}  // namespace assets
